# Generated by Django 2.2.2 on 2021-10-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productgallary_productseosection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallary',
            old_name='product',
            new_name='image_product',
        ),
        migrations.RenameField(
            model_name='productseosection',
            old_name='product',
            new_name='seo_product',
        ),
    ]
