# Generated by Django 2.2.2 on 2021-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211008_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseosection',
            name='seo_keywords',
            field=models.CharField(max_length=500),
        ),
    ]
