# Generated by Django 2.2.2 on 2021-10-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_blogs_blogscategory_blogsseosection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsseosection',
            old_name='bog',
            new_name='seo_blogs',
        ),
    ]
