# Generated by Django 2.2.2 on 2021-10-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211009_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsseosection',
            old_name='seo_desccription',
            new_name='seo_description',
        ),
    ]
