# Generated by Django 2.2.2 on 2021-10-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211009_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsseosection',
            old_name='seo_blogs',
            new_name='seo_blog',
        ),
    ]
